import { v4 as uuidv4 } from 'uuid';

const genderListData = [
    { id: uuidv4(), genderName: 'Action' },
    { id: uuidv4(), genderName: 'Adventure' },
    { id: uuidv4(), genderName: 'Comedy' },
    { id: uuidv4(), genderName: 'Drama' },
    { id: uuidv4(), genderName: 'Slice of life' },
    { id: uuidv4(), genderName: 'Ecchi' },
    { id: uuidv4(), genderName: 'Fantasy' },
    { id: uuidv4(), genderName: 'Magic' },
    { id: uuidv4(), genderName: 'Supernatural' },
    { id: uuidv4(), genderName: 'Horror' },
    { id: uuidv4(), genderName: 'Mystery' },
    { id: uuidv4(), genderName: 'Psychological' },
    { id: uuidv4(), genderName: 'Romance' },
    { id: uuidv4(), genderName: 'Science Fiction' },
    { id: uuidv4(), genderName: 'Thriler' },
    { id: uuidv4(), genderName: 'Sport' },
    { id: uuidv4(), genderName: 'Girls Love' },
    { id: uuidv4(), genderName: 'Boys Love' },
    { id: uuidv4(), genderName: 'Harem' },
    { id: uuidv4(), genderName: 'Mecha' },
    { id: uuidv4(), genderName: 'survival' },
    { id: uuidv4(), genderName: 'Reincarnation' },
    { id: uuidv4(), genderName: 'Gore' },
    { id: uuidv4(), genderName: 'Apocalyptic' },
    { id: uuidv4(), genderName: 'Tragedy' },
    { id: uuidv4(), genderName: 'School Life' },
    { id: uuidv4(), genderName: 'Story' },
    { id: uuidv4(), genderName: 'Military' },
    { id: uuidv4(), genderName: 'Police' },
    { id: uuidv4(), genderName: 'Crime' },
    { id: uuidv4(), genderName: 'Superpowers' },
    { id: uuidv4(), genderName: 'Vampires' },
    { id: uuidv4(), genderName: 'Martial Arts' },
    { id: uuidv4(), genderName: 'Samurai' },
    { id: uuidv4(), genderName: 'Genus bender' },
    { id: uuidv4(), genderName: 'Virtual reality' },
    { id: uuidv4(), genderName: 'Cyberpunk' },
    { id: uuidv4(), genderName: 'Music' },
    { id: uuidv4(), genderName: 'Parody' },
    { id: uuidv4(), genderName: 'Animation' },
    { id: uuidv4(), genderName: 'Demons' },
    { id: uuidv4(), genderName: 'Family' },
    { id: uuidv4(), genderName: 'Foreign' },
    { id: uuidv4(), genderName: 'Kids' },
    { id: uuidv4(), genderName: 'Reality' },
    { id: uuidv4(), genderName: 'Soap opera' },
    { id: uuidv4(), genderName: 'War' },
    { id: uuidv4(), genderName: 'West' },




];
export default genderListData;